# -*- coding: utf-8 -*-
"""
Created on 2021-09-16 21:33:04
---------
@summary:
---------
@author: root
"""

from feapder import Item, UpdateItem


class BlogThemeItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i blog_theme.
    """

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.url = ""
        #self.name = ""
        self.state = 0

    def pre_to_db(self):
        """
        入库前的处理
        """
        if self.name :
            self.name = self.name.strip()
        else:
            self.name = ""