# -*- coding: utf-8 -*-
"""
Created on 2021-09-17 15:24:19
---------
@summary:
---------
@author: root
"""

from feapder import Item, UpdateItem

class DbtTalkBlogItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i dbt_talk_blog.
    """
    #__update_key__ = ["title"] # 更新title字段

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.url = ""
        self.title = ""
        # self.title_ch = ""
        # self.theme_id = NULL
    
    def pre_to_db(self):
        if self.title :
            self.title = self.title.replace('-',' ')