# -*- coding: utf-8 -*-
"""
Created on 2021-09-16 14:00:56
---------
@summary:
---------
@author: root
"""

from feapder import Item, UpdateItem


class ExternalLinkItem(Item):
    """
    This class was generated by feapder.
    command: feapder create -i dbt_talk_blog.
    """
    __update_key__ = ["content"] # 更新content字段

    def __init__(self, *args, **kwargs):
        # self.id = None
        #self.url = null
        self.content = ""
        #self.title = ""

    def pre_to_db(self):
        """
        入库前的处理
        """
        

